laguage: bash
addons:
        apt:
                sources:
                        - sourceline:'ppa:duggan/bats'
                packages:
                        - bats
                        - bc
script:
  - echo "課題４テス"
  - echo "Start Travis-CI test in .travis.yml"
  - ./20745106_kadai4_test.sh
